"""Combine the temporal cue model with a VLM's per-student opinion.

Two models answer the same question about the same student, and this decides
what to show.

Why the default policy is agreement-gating rather than a product of experts
-------------------------------------------------------------------------
Multiplying or averaging two probability vectors assumes they live on the same
scale. They do not:

* the temporal model's probabilities are temperature-scaled against a fitted
  calibration (``runtime/dashboard/*.json``), so 0.7 means something;
* a VLM's option likelihoods are not calibrated at all. They are logits over
  answer tokens, sensitive to prompt wording and option order.

Pooling them would let the uncalibrated half dominate wherever it happens to be
confident, and the result would look like a probability while being none.
``AGREEMENT`` uses only each model's argmax, which needs no shared scale, and
reports disagreement instead of averaging it away. POOL and PRODUCT are
provided because they are the obvious baselines to compare against, and are
documented as requiring the VLM side to be calibrated first.

The independence caveat
-----------------------
A fusion earns its keep when the two models fail differently. The temporal
model was trained on labels generated by Qwen3.5-27B; a Qwen-family VLM is
therefore not a fully independent second opinion, and agreement between them
partly measures shared bias. Using a *different-sized* base model that was
never adapted to these labels weakens that, but does not remove it. Any
agreement rate reported from this module must carry that caveat.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Sequence

import numpy as np

from .taxonomy import CUE_CLASSES

NUM_CUES = len(CUE_CLASSES)


class Policy(str, Enum):
    #: Show the label only when both models agree; otherwise report contested.
    AGREEMENT = "agreement"
    #: Linear opinion pool, weight on the temporal model.
    POOL = "pool"
    #: Product of experts, renormalised.
    PRODUCT = "product"


@dataclass
class FusedStudent:
    """What the dashboard shows for one student."""
    temporal_cue: str
    temporal_conf: float
    vlm_cue: Optional[str] = None
    vlm_conf: Optional[float] = None
    #: The cue to display, or None when the policy declines to pick one.
    cue: Optional[str] = None
    agree: Optional[bool] = None
    contested: bool = False
    policy: str = Policy.AGREEMENT.value
    #: Only populated by POOL/PRODUCT; None under AGREEMENT, which never
    #: constructs a combined distribution.
    fused: Optional[List[float]] = None
    note: str = ""

    def to_json(self) -> Dict:
        return {
            "cue": self.cue,
            "temporal": {"cue": self.temporal_cue,
                         "conf": round(float(self.temporal_conf), 4)},
            "vlm": (None if self.vlm_cue is None else
                    {"cue": self.vlm_cue, "conf": round(float(self.vlm_conf), 4)}),
            "agree": self.agree,
            "contested": self.contested,
            "policy": self.policy,
            "note": self.note,
        }


def _as_probs(v: Sequence[float], k: int = NUM_CUES) -> np.ndarray:
    a = np.asarray(v, dtype=np.float64)
    if a.shape != (k,):
        raise ValueError(f"expected {k} cue scores, got {a.shape}")
    if (a < 0).any():
        raise ValueError("cue scores must be non-negative probabilities")
    s = a.sum()
    if s <= 0:
        raise ValueError("cue scores sum to zero")
    return a / s


def fuse_student(temporal: Sequence[float],
                 vlm: Optional[Sequence[float]] = None,
                 policy: Policy = Policy.AGREEMENT,
                 temporal_weight: float = 0.5,
                 classes: Optional[Sequence[str]] = None) -> FusedStudent:
    """Combine one student's two opinions.

    ``temporal`` and ``vlm`` are probability vectors over ``classes``, which
    defaults to the six cue classes. ``vlm`` may be None -- the VLM is optional
    and slower, so the system must stay correct without it rather than degrade
    to nothing.

    ``classes`` must be the SAME list the grounder scored against. Both vectors
    are indexed positionally, so a mismatch does not raise, it silently pairs
    every cue with the wrong name.
    """
    cl = list(CUE_CLASSES if classes is None else classes)
    k = len(cl)
    t = _as_probs(temporal, k)
    t_id = int(t.argmax())
    out = FusedStudent(temporal_cue=cl[t_id], temporal_conf=float(t[t_id]),
                       policy=policy.value)

    if vlm is None:
        out.cue = out.temporal_cue
        out.note = "temporal only; no VLM opinion for this student"
        return out

    v = _as_probs(vlm, k)
    v_id = int(v.argmax())
    out.vlm_cue = cl[v_id]
    out.vlm_conf = float(v[v_id])
    out.agree = t_id == v_id

    if policy is Policy.AGREEMENT:
        if out.agree:
            out.cue = out.temporal_cue
            out.note = "both models agree"
        else:
            # Deliberately no winner. Picking the more confident one would be
            # comparing a calibrated probability against an uncalibrated one.
            out.cue = None
            out.contested = True
            out.note = (f"contested: temporal says {out.temporal_cue}, "
                        f"VLM says {out.vlm_cue}")
        return out

    if policy is Policy.POOL:
        w = float(np.clip(temporal_weight, 0.0, 1.0))
        f = w * t + (1.0 - w) * v
    elif policy is Policy.PRODUCT:
        f = t * v
        if f.sum() <= 0:                      # disjoint supports
            out.cue = None
            out.contested = True
            out.note = ("contested: the two distributions have no overlapping "
                        "support, so their product is undefined")
            return out
    else:                                     # pragma: no cover - Enum is closed
        raise ValueError(f"unknown policy {policy!r}")

    f = f / f.sum()
    f_id = int(f.argmax())
    out.fused = [float(x) for x in f]
    out.cue = cl[f_id]
    out.contested = not out.agree
    out.note = (f"{policy.value}: {out.cue}"
                + ("" if out.agree else
                   f" (models disagreed: {out.temporal_cue} vs {out.vlm_cue})"))
    return out


def fuse_frame(temporal: Dict[int, Sequence[float]],
               vlm: Optional[Dict[int, Sequence[float]]] = None,
               policy: Policy = Policy.AGREEMENT,
               temporal_weight: float = 0.5,
               classes: Optional[Sequence[str]] = None) -> Dict[int, FusedStudent]:
    """Fuse every tracked student in one frame, keyed by track id.

    A student present in ``temporal`` but missing from ``vlm`` is fused as
    temporal-only rather than dropped: the VLM runs at a lower rate than the
    tracker, so gaps are normal and must not remove students from the display.
    """
    vlm = vlm or {}
    return {tid: fuse_student(t, vlm.get(tid), policy, temporal_weight, classes)
            for tid, t in temporal.items()}


def agreement_summary(fused: Dict[int, FusedStudent]) -> Dict:
    """Class-level agreement, for the dashboard header and for reporting.

    ``rate`` is over students where BOTH models spoke; students the VLM did not
    see are excluded rather than counted as agreeing, which would inflate it.
    """
    both = [f for f in fused.values() if f.agree is not None]
    agree = sum(1 for f in both if f.agree)
    return {
        "n_students": len(fused),
        "n_compared": len(both),
        "n_agree": agree,
        "n_contested": len(both) - agree,
        "rate": (agree / len(both)) if both else None,
        "by_cue": {
            c: {
                "temporal": sum(1 for f in fused.values() if f.temporal_cue == c),
                "vlm": sum(1 for f in fused.values() if f.vlm_cue == c),
            } for c in CUE_CLASSES
        },
    }
